---
- name: restart mongo
  service:
    name: mongo
    state: restarted
    enabled: true

- name: reload mongo
  service:
    name: mongo
    state: reloaded
    enabled: true

- name: start mongo
  service:
    name: mongo
    state: started
    enabled: true
